using System;
using System.Collections.Generic;
using System.Linq;
using Archipelago.Helpers;
using PerfectRandom.Sulfur.Core;

namespace Archipelago.Archipelago;

public static class ArchipelagoItems
{
    private static readonly IList<Item> AllItems = new List<Item>
    {
        new ItemPickup(1, "Ammo Box (12ga)", ItemIds.Ammo_12Ga),
        new ItemPickup(2, "Ammo Box (50 BMG)", ItemIds.Ammo_50BMG),
        new ItemPickup(3, "Ammo Box (5.56mm)", ItemIds.Ammo_556),
        new ItemPickup(4, "Ammo Box (7.62mm)", ItemIds.Ammo_762),
        new ItemPickup(5, "Ammo Box (9mm)", ItemIds.Ammo_9mm),
        new ItemPickup(6, "Ammo Box (Energy Cells)", ItemIds.Ammo_EnergyCell),
        new ItemPickup(7, "Blood of the Earth Mother", ItemIds.AmuletCharge),
        new ItemPickup(8, "A12C Muzzle Brake", ItemIds.Attachment_A12CMuzzleBrake),
        new ItemPickup(9, "Assault Scope", ItemIds.Attachment_AssaultScope),
        new ItemPickup(10, "Barrel Extension 2\"", ItemIds.Attachment_BarrelExtension2i),
        new ItemPickup(11, "Barrel Extension 4\"", ItemIds.Attachment_BarrelExtension4i),
        new ItemPickup(12, "Barrel Extension 6\"", ItemIds.Attachment_BarrelExtension6i),
        new ItemPickup(13, "Breznik BMD", ItemIds.Attachment_BreznikBMD),
        new ItemPickup(14, "Breznik BMD (Tactical)", ItemIds.Attachment_BreznikBMDTactical),
        new ItemPickup(15, "Compact Sight", ItemIds.Attachment_CompactSight),
        new ItemPickup(16, "Gun Crank", ItemIds.Attachment_GunCrank),
        new ItemPickup(17, "Haukland Flash Hider", ItemIds.Attachment_HauklandFlashHider),
        new ItemPickup(18, "Holographic Sight", ItemIds.Attachment_HolographicSight),
        new ItemPickup(19, "Hunting Scope", ItemIds.Attachment_HuntingScope),
        new ItemPickup(20, "Improvised Barrel Extension", ItemIds.Attachment_ImprovisedBarrelExtension),
        new ItemPickup(21, "Insurance", ItemIds.Attachment_Insurance),
        new ItemPickup(22, "Laser Sight (Green)", ItemIds.Attachment_LaserSightGreen),
        new ItemPickup(23, "Laser Sight (Red)", ItemIds.Attachment_LaserSightRed),
        new ItemPickup(24, "Laser Sight (Yellow)", ItemIds.Attachment_LaserSightYellow),
        new ItemPickup(25, "Priming Bolt", ItemIds.Attachment_PrimingBolt),
        new ItemPickup(26, "Recon Scope", ItemIds.Attachment_ReconScope),
        new ItemPickup(27, "Reflex Sight", ItemIds.Attachment_ReflexSight),
        new ItemPickup(28, "Shrouded Barrel Extension", ItemIds.Attachment_ShroudedBarrelExtension),
        new ItemPickup(29, "Sniper Scope", ItemIds.Attachment_SniperScope),
        new ItemPickup(30, "Haukland Silencer", ItemIds.Attachment_Suppressor556),
        new ItemPickup(31, "Aftermarket Haukland Silencer", ItemIds.Attachment_Suppressor762),
        new ItemPickup(32, "SR-P3 Silencer", ItemIds.Attachment_Suppressor9mm),
        new ItemPickup(33, "M87 \"Albatross\" Silencer", ItemIds.Attachment_SuppressorCan),
        new ItemPickup(34, "Warmage Compensator", ItemIds.Attachment_WarmageCompensator),
        new ItemPickup(35, "Chamber Chisel (12ga)", ItemIds.Consumable_ChamberChisel12ga),
        new ItemPickup(36, "Chamber Chisel (.50 BMG)", ItemIds.Consumable_ChamberChisel50BMG),
        new ItemPickup(37, "Chamber Chisel (5.56mm)", ItemIds.Consumable_ChamberChisel556),
        new ItemPickup(38, "Chamber Chisel (7.62mm)", ItemIds.Consumable_ChamberChisel762),
        new ItemPickup(39, "Chamber Chisel (9mm)", ItemIds.Consumable_ChamberChisel9mm),
        new ItemSulf(40, "Cash Money Bill", 100),
        new ItemSulf(41, "Cash Money Coin", 1),
        new ItemSulf(42, "Cash Money Twenny", 20),
        new ItemPickup(43, "Action Oil", ItemIds.Enchantment_ActionOil),
        new ItemPickup(44, "Add Damage Oil", ItemIds.Enchantment_AddDamageOil),
        new ItemPickup(45, "Scroll of Aftershock", ItemIds.Enchantment_Aftershock),
        new ItemPickup(46, "Aimless Oil", ItemIds.Enchantment_AimlessOil),
        new ItemPickup(47, "Airsoft Oil", ItemIds.Enchantment_AirSoftOil),
        new ItemPickup(48, "Altruistic Oil", ItemIds.Enchantment_AltruisticOil),
        new ItemPickup(49, "Arkanoid Oil", ItemIds.Enchantment_ArkanoidOil),
        new ItemPickup(50, "Arrow Oil", ItemIds.Enchantment_ArrowOil),
        new ItemPickup(51, "Artery Oil", ItemIds.Enchantment_ArteryOil),
        new ItemPickup(52, "Artillery Oil", ItemIds.Enchantment_ArtilleryOil),
        new ItemPickup(53, "Ascetic Oil", ItemIds.Enchantment_AsceticOil),
        new ItemPickup(54, "Assassin Dart Oil", ItemIds.Enchantment_AssassinDartOil),
        new ItemPickup(55, "Attack Speed Oil", ItemIds.Enchantment_AttackSpeedOil),
        new ItemPickup(56, "Axe Oil", ItemIds.Enchantment_AxeOil),
        new ItemPickup(57, "Bad Planet Oil", ItemIds.Enchantment_BadPlanetOil),
        new ItemPickup(58, "Bandit Oil", ItemIds.Enchantment_BanditOil),
        new ItemPickup(59, "BB Oil", ItemIds.Enchantment_BBOil),
        new ItemPickup(60, "Bigger Bullets Oil", ItemIds.Enchantment_Big),
        new ItemPickup(61, "Big Oil", ItemIds.Enchantment_BigOil),
        new ItemPickup(62, "Big Tax Oil", ItemIds.Enchantment_BigTaxOil),
        new ItemPickup(63, "Birth Oil", ItemIds.Enchantment_BirthOil),
        new ItemPickup(64, "Black Friday Oil", ItemIds.Enchantment_BlackFridayOil),
        new ItemPickup(65, "Blindfold Oil", ItemIds.Enchantment_BlindfoldOil),
        new ItemPickup(66, "Blurt Oil", ItemIds.Enchantment_BlurtOil),
        new ItemPickup(67, "Bolt Oil", ItemIds.Enchantment_BoltOil),
        new ItemPickup(68, "Bombard Oil", ItemIds.Enchantment_BombardOil),
        new ItemPickup(69, "Boomstick Oil", ItemIds.Enchantment_BoomstickOil),
        new ItemPickup(70, "Boulder Oil", ItemIds.Enchantment_BoulderOil),
        new ItemPickup(71, "Bouncing Bullets Oil", ItemIds.Enchantment_Bounce),
        new ItemPickup(72, "Bowl Oil", ItemIds.Enchantment_BowlOil),
        new ItemPickup(73, "Braced Oil", ItemIds.Enchantment_BracedOil),
        new ItemPickup(74, "Brutality Oil", ItemIds.Enchantment_Brutality),
        new ItemPickup(75, "Brute Oil", ItemIds.Enchantment_BruteOil),
        new ItemPickup(76, "Bulk Oil", ItemIds.Enchantment_BulkOil),
        new ItemPickup(77, "Bystander Oil", ItemIds.Enchantment_BystanderOil),
        new ItemPickup(78, "Carefree Oil", ItemIds.Enchantment_CarefreeOil),
        new ItemPickup(79, "Careful Oil", ItemIds.Enchantment_CarefulOil),
        new ItemPickup(80, "Careless Splitter Oil", ItemIds.Enchantment_CarelessSplitterOil),
        new ItemPickup(81, "Cartoon Oil", ItemIds.Enchantment_CartoonOil),
        new ItemPickup(82, "Casual Oil", ItemIds.Enchantment_CasualOil),
        new ItemPickup(83, "Scroll of Chain Lightning", ItemIds.Enchantment_ChainLightning),
        new ItemPickup(84, "Scroll of Chaos Strike", ItemIds.Enchantment_ChaosStrike),
        new ItemPickup(85, "Scroll of Charm", ItemIds.Enchantment_Charm),
        new ItemPickup(86, "Cheap Oil", ItemIds.Enchantment_CheapOil),
        new ItemPickup(87, "Chonk Oil", ItemIds.Enchantment_ChonkOil),
        new ItemPickup(88, "Chub Oil", ItemIds.Enchantment_ChubOil),
        new ItemPickup(89, "Clump Oil", ItemIds.Enchantment_ClumpOil),
        new ItemPickup(90, "Collateral Oil", ItemIds.Enchantment_CollateralOil),
        new ItemPickup(91, "Complicated Oil", ItemIds.Enchantment_ComplicatedOil),
        new ItemPickup(92, "Compo Oil", ItemIds.Enchantment_CompoOil),
        new ItemPickup(93, "Confidence Oil", ItemIds.Enchantment_ConfidenceOil),
        new ItemPickup(94, "Congestion Oil", ItemIds.Enchantment_CongestionOil),
        new ItemPickup(95, "Considerate Oil", ItemIds.Enchantment_ConsiderateOil),
        new ItemPickup(96, "Contained Force Oil", ItemIds.Enchantment_ContainedForceOil),
        new ItemPickup(97, "Scroll of Corpse Explosion", ItemIds.Enchantment_CorpseExplosion),
        new ItemPickup(98, "Scroll of Poison Blood", ItemIds.Enchantment_CorrosiveBlood),
        new ItemPickup(99, "Critical Oil", ItemIds.Enchantment_CriticalOil),
        new ItemPickup(100, "Scroll of Crusader", ItemIds.Enchantment_Crusader),
        new ItemPickup(101, "Cycle Oil", ItemIds.Enchantment_CycleOil),
        new ItemPickup(102, "Damage Oil", ItemIds.Enchantment_DamageOil),
        new ItemScroll(103, "Scroll of Dark", ItemIds.Enchantment_Dark),
        new ItemPickup(104, "Dart Oil", ItemIds.Enchantment_DartOil),
        new ItemPickup(105, "Dead Center Oil", ItemIds.Enchantment_DeadCenterOil),
        new ItemPickup(106, "Delayed Hyper Tube Oil", ItemIds.Enchantment_DelayedHyperTubeOil),
        new ItemPickup(107, "Dense Oil", ItemIds.Enchantment_DenseOil),
        new ItemPickup(108, "Detune Oil", ItemIds.Enchantment_DetuneOil),
        new ItemPickup(109, "Diesel Oil", ItemIds.Enchantment_DieselOil),
        new ItemPickup(110, "Discharge Oil", ItemIds.Enchantment_DischargeOil),
        new ItemPickup(111, "Disposable Oil", ItemIds.Enchantment_DisposableOil),
        new ItemPickup(112, "Division Oil", ItemIds.Enchantment_DivisionOil),
        new ItemPickup(113, "Do-over Oil", ItemIds.Enchantment_DoOverOil),
        new ItemPickup(114, "Double Fire Oil", ItemIds.Enchantment_DoubleFireOil),
        new ItemPickup(115, "Double Lock Oil", ItemIds.Enchantment_DoubleLockOil),
        new ItemPickup(116, "Double Nothing Oil", ItemIds.Enchantment_DoubleNothingOil),
        new ItemPickup(117, "Oil of Yin", ItemIds.Enchantment_Duality),
        new ItemPickup(118, "Dum Dum Oil", ItemIds.Enchantment_DumDumOil),
        new ItemPickup(119, "Dynamic Oil", ItemIds.Enchantment_DynamicOil),
        new ItemScroll(120, "Scroll of Earth", ItemIds.Enchantment_Earth),
        new ItemPickup(121, "Easy Oil", ItemIds.Enchantment_EasyOil),
        new ItemPickup(122, "Easy Plop Oil", ItemIds.Enchantment_EasyPlopOil),
        new ItemScroll(123, "Scroll of Surge", ItemIds.Enchantment_Electricity),
        new ItemPickup(124, "Elephant Oil", ItemIds.Enchantment_ElephantOil),
        new ItemPickup(125, "Eternal Oil", ItemIds.Enchantment_EternalOil),
        new ItemPickup(126, "Exotic Barrel Oil", ItemIds.Enchantment_ExoticBarrelOil),
        new ItemPickup(127, "Expander Oil", ItemIds.Enchantment_ExpanderOil),
        new ItemPickup(128, "Extra Powder Oil", ItemIds.Enchantment_ExtraPowderOil),
        new ItemPickup(129, "Farsighted Oil", ItemIds.Enchantment_FarsightedOil),
        new ItemPickup(130, "Fast Bet Oil", ItemIds.Enchantment_FastBetOil),
        new ItemPickup(131, "Fast Forward Oil", ItemIds.Enchantment_FastForwardOil),
        new ItemPickup(132, "Scroll of Fear", ItemIds.Enchantment_Fear),
        new ItemPickup(133, "Feature Gun Oil", ItemIds.Enchantment_FeatureGun),
        new ItemPickup(134, "Fidget Lord Oil", ItemIds.Enchantment_FidgetLordOil),
        new ItemPickup(135, "Fidget Oil", ItemIds.Enchantment_FidgetOil),
        new ItemScroll(136, "Scroll of Embers", ItemIds.Enchantment_Fire),
        new ItemPickup(137, "First Blood Oil", ItemIds.Enchantment_FirstBloodOil),
        new ItemPickup(138, "Scroll of Flame Thrower", ItemIds.Enchantment_FlameThrower),
        new ItemPickup(139, "Flea Oil", ItemIds.Enchantment_FleaOil),
        new ItemPickup(140, "Flop Oil", ItemIds.Enchantment_FlopOil),
        new ItemPickup(141, "Flow Funnel Oil", ItemIds.Enchantment_FlowFunnelOil),
        new ItemPickup(142, "Rate of Fire Oil", ItemIds.Enchantment_Flutter),
        new ItemPickup(143, "Food Stamp Oil", ItemIds.Enchantment_FoodStampOil),
        new ItemPickup(144, "Force Oil", ItemIds.Enchantment_ForceOil),
        new ItemPickup(145, "Fragile System Oil", ItemIds.Enchantment_FragileSystemOil),
        new ItemPickup(146, "Franciscan Oil", ItemIds.Enchantment_FranciscanOil),
        new ItemScroll(147, "Scroll of Frostbite", ItemIds.Enchantment_Frost),
        new ItemPickup(148, "Frugal Oil", ItemIds.Enchantment_FrugalOil),
        new ItemPickup(149, "Gambler Oil", ItemIds.Enchantment_GamblerOil),
        new ItemPickup(150, "Gargantuan Oil", ItemIds.Enchantment_GargantuanOil),
        new ItemPickup(151, "Gemini Oil", ItemIds.Enchantment_GeminiOil),
        new ItemPickup(152, "Gentle Oil", ItemIds.Enchantment_GentleOil),
        new ItemPickup(153, "Glass Cannon Oil", ItemIds.Enchantment_GlassCannonOil),
        new ItemPickup(154, "Great Oil", ItemIds.Enchantment_GreatOil),
        new ItemPickup(155, "Grounded Oil", ItemIds.Enchantment_GroundedOil),
        new ItemPickup(156, "Gunslinger Oil", ItemIds.Enchantment_GunslingerOil),
        new ItemPickup(157, "Happy Accident Oil", ItemIds.Enchantment_HappyAccidentOil),
        new ItemPickup(158, "Heavy Lead Oil", ItemIds.Enchantment_HeavyLeadOil),
        new ItemPickup(159, "Heavy Oil", ItemIds.Enchantment_HeavyOil),
        new ItemPickup(160, "Heavy Pockets  Oil", ItemIds.Enchantment_HeavyPocketsOil),
        new ItemPickup(161, "Hefty Oil", ItemIds.Enchantment_HeftyOil),
        new ItemPickup(162, "Helium Oil", ItemIds.Enchantment_HeliumOil),
        new ItemPickup(163, "High Grade Oil", ItemIds.Enchantment_HighGradeOil),
        new ItemPickup(164, "Hip Blaster Oil", ItemIds.Enchantment_HipBlasterOil),
        new ItemPickup(165, "Hip Marksman Oil", ItemIds.Enchantment_HipMarksmanOil),
        new ItemPickup(166, "Scroll of Holy Fire", ItemIds.Enchantment_HolyFire),
        new ItemPickup(167, "Scroll of Holy Purge", ItemIds.Enchantment_HolyPurge),
        new ItemPickup(168, "Hoop Oil", ItemIds.Enchantment_HoopOil),
        new ItemPickup(169, "Hunter Oil", ItemIds.Enchantment_HunterOil),
        new ItemPickup(170, "Hustler Oil", ItemIds.Enchantment_HustlerOil),
        new ItemPickup(171, "Hyper Lead Oil", ItemIds.Enchantment_HyperLeadOil),
        new ItemPickup(172, "Imperfect Oil", ItemIds.Enchantment_ImperfectOil),
        new ItemPickup(173, "Inconsiderate Oil", ItemIds.Enchantment_InconsiderateOil),
        new ItemPickup(174, "Inherited Oil", ItemIds.Enchantment_InheritedOil),
        new ItemPickup(175, "Instant Oil", ItemIds.Enchantment_InstantOil),
        new ItemPickup(176, "Judgement Oil", ItemIds.Enchantment_JudgementOil),
        new ItemPickup(177, "Jungian Oil", ItemIds.Enchantment_JungianOil),
        new ItemPickup(178, "Keep Oil", ItemIds.Enchantment_KeepOil),
        new ItemPickup(179, "Kicker Oil", ItemIds.Enchantment_KickerOil),
        new ItemPickup(180, "Kinetic Oil", ItemIds.Enchantment_KineticOil),
        new ItemPickup(181, "Last Drop Oil", ItemIds.Enchantment_LastDropOil),
        new ItemPickup(182, "Late Boom Oil", ItemIds.Enchantment_LateBoomOil),
        new ItemPickup(183, "Launcher Oil", ItemIds.Enchantment_LauncherOil),
        new ItemPickup(184, "Scroll of Lava", ItemIds.Enchantment_Lava),
        new ItemPickup(185, "Lazy Oil", ItemIds.Enchantment_LazyOil),
        new ItemPickup(186, "Scroll of Least Resistance", ItemIds.Enchantment_LeastResistance),
        new ItemPickup(187, "Less Recoil Oil", ItemIds.Enchantment_LessRecoilOil),
        new ItemScroll(188, "Scroll of Light", ItemIds.Enchantment_Light),
        new ItemPickup(189, "Lightweight Oil", ItemIds.Enchantment_LightweightOil),
        new ItemPickup(190, "Longshot Oil", ItemIds.Enchantment_LongshotOil),
        new ItemPickup(191, "Lost In Focus Oil", ItemIds.Enchantment_LostInFocusOil),
        new ItemPickup(192, "Low Roller Oil", ItemIds.Enchantment_LowRollerOil),
        new ItemPickup(193, "Machine Oil", ItemIds.Enchantment_MachineOil),
        new ItemPickup(194, "Main Discipline Oil", ItemIds.Enchantment_MainDisciplineOil),
        new ItemPickup(195, "Main Focus Oil", ItemIds.Enchantment_MainFocusOil),
        new ItemPickup(196, "Manifestation Oil", ItemIds.Enchantment_ManifestationOil),
        new ItemPickup(197, "Matrix Oil", ItemIds.Enchantment_MatrixOil),
        new ItemPickup(198, "Micro Wing Oil", ItemIds.Enchantment_MicroWingOil),
        new ItemPickup(199, "Modern Technology Oil", ItemIds.Enchantment_ModernTechnologyOil),
        new ItemPickup(200, "Mosquito Oil", ItemIds.Enchantment_MosquitoOil),
        new ItemPickup(201, "Multichamber Oil", ItemIds.Enchantment_MultichamberOil),
        new ItemPickup(202, "Multishot Oil", ItemIds.Enchantment_MultishotOil),
        new ItemScroll(203, "Scroll of Nature", ItemIds.Enchantment_Nature),
        new ItemPickup(204, "Needleye Oil", ItemIds.Enchantment_NeedleeyeOil),
        new ItemPickup(205, "Nerf Oil", ItemIds.Enchantment_NerfOil),
        new ItemPickup(206, "No Look Oil", ItemIds.Enchantment_NoLookOil),
        new ItemPickup(207, "No Need Oil", ItemIds.Enchantment_NoNeedOil),
        new ItemPickup(208, "Scroll of Noxiosa", ItemIds.Enchantment_Noxiosa),
        new ItemPickup(209, "Out of the Box Oil", ItemIds.Enchantment_OutOfTheBoxOil),
        new ItemPickup(210, "Overclock Oil", ItemIds.Enchantment_OverclockOil),
        new ItemPickup(211, "Overdose Oil", ItemIds.Enchantment_OverdoseOil),
        new ItemPickup(212, "Over Oil", ItemIds.Enchantment_OverOil),
        new ItemPickup(213, "Parallel Mag Oil", ItemIds.Enchantment_ParallelMagOil),
        new ItemPickup(214, "Peashooter Oil", ItemIds.Enchantment_PeashooterOil),
        new ItemPickup(215, "Penetration Oil", ItemIds.Enchantment_PenetrationOil),
        new ItemPickup(216, "Perfect Bounce Oil", ItemIds.Enchantment_PerfectBounceOil),
        new ItemPickup(217, "Perforate Oil", ItemIds.Enchantment_PerforateOil),
        new ItemPickup(218, "Scroll of Pesticide", ItemIds.Enchantment_Pesticide),
        new ItemPickup(219, "Scroll of Petrification", ItemIds.Enchantment_Petrification),
        new ItemPickup(220, "Scroll of Petroleum", ItemIds.Enchantment_Petroleum),
        new ItemPickup(221, "Plinker Oil", ItemIds.Enchantment_PlinkerOil),
        new ItemPickup(222, "Plop Back Oil", ItemIds.Enchantment_PlopBackOil),
        new ItemScroll(223, "Scroll of Plague", ItemIds.Enchantment_Poison),
        new ItemPickup(224, "Pool Oil", ItemIds.Enchantment_PoolOil),
        new ItemPickup(225, "Potato Oil", ItemIds.Enchantment_PotatoOil),
        new ItemPickup(226, "Potshot Oil", ItemIds.Enchantment_PotShotOil),
        new ItemPickup(227, "Scroll of Prism", ItemIds.Enchantment_Prism),
        new ItemPickup(228, "Puncher Oil", ItemIds.Enchantment_PuncherOil),
        new ItemPickup(229, "Puncture Oil", ItemIds.Enchantment_PunctureOil),
        new ItemPickup(230, "Purse Gun Oil", ItemIds.Enchantment_PurseGunOil),
        new ItemPickup(231, "Scroll of Explosions", ItemIds.Enchantment_Pyroclasm),
        new ItemPickup(232, "Rapid Internals Oil", ItemIds.Enchantment_RapidInternalsOil),
        new ItemPickup(233, "Ready Oil", ItemIds.Enchantment_ReadyOil),
        new ItemPickup(234, "Rebound Oil", ItemIds.Enchantment_ReboundOil),
        new ItemPickup(235, "Recycle Oil", ItemIds.Enchantment_RecycleOil),
        new ItemPickup(236, "Relax Oil", ItemIds.Enchantment_RelaxOil),
        new ItemPickup(237, "Release Oil", ItemIds.Enchantment_ReleaseOil),
        new ItemPickup(238, "Reload Oil", ItemIds.Enchantment_ReloadOil),
        new ItemPickup(239, "Ricochet Oil", ItemIds.Enchantment_RicochetOil),
        new ItemPickup(240, "Rigid System Oil", ItemIds.Enchantment_RigidSystemOil),
        new ItemPickup(241, "Rigor Oil", ItemIds.Enchantment_RigorOil),
        new ItemPickup(242, "Robust Mechanics Oil", ItemIds.Enchantment_RobustMechanicsOil),
        new ItemPickup(243, "Scroll of Rocket Launcher", ItemIds.Enchantment_RocketLauncher),
        new ItemPickup(244, "Rookie Oil", ItemIds.Enchantment_RookieOil),
        new ItemPickup(245, "Rubber Oil", ItemIds.Enchantment_RubberOil),
        new ItemPickup(246, "Rush Job Oil", ItemIds.Enchantment_RushJobOil),
        new ItemPickup(247, "Scroll of Sacrifice", ItemIds.Enchantment_Sacrifice),
        new ItemPickup(248, "Safety Oil", ItemIds.Enchantment_SafetyOil),
        new ItemPickup(249, "Translucent Oil", ItemIds.Enchantment_Satiety),
        new ItemPickup(250, "Saviour Oil", ItemIds.Enchantment_SaviourOil),
        new ItemPickup(251, "Scatter Oil", ItemIds.Enchantment_ScatterOil),
        new ItemPickup(252, "Scramble Oil", ItemIds.Enchantment_ScrambleOil),
        new ItemPickup(253, "Seated Fit Oil", ItemIds.Enchantment_SeatedFitOil),
        new ItemPickup(254, "Seated Oil", ItemIds.Enchantment_SeatedOil),
        new ItemPickup(255, "Sect Oil", ItemIds.Enchantment_SectOil),
        new ItemPickup(256, "Sender Oil", ItemIds.Enchantment_SenderOil),
        new ItemPickup(257, "Sensible Oil", ItemIds.Enchantment_SensibleOil),
        new ItemPickup(258, "Shaved Clip Oil", ItemIds.Enchantment_ShavedClipOil),
        new ItemPickup(259, "Shellman Oil", ItemIds.Enchantment_ShellManOil),
        new ItemPickup(260, "Sherlock Oil", ItemIds.Enchantment_SherlockOil),
        new ItemPickup(261, "Shower Oil", ItemIds.Enchantment_ShowerOil),
        new ItemPickup(262, "Shredder Oil", ItemIds.Enchantment_ShredderOil),
        new ItemPickup(263, "Size Up Oil", ItemIds.Enchantment_SizeUpOil),
        new ItemPickup(264, "Skip Oil", ItemIds.Enchantment_SkipOil),
        new ItemPickup(265, "Crit Oil", ItemIds.Enchantment_Slayer),
        new ItemPickup(266, "Slick Oil", ItemIds.Enchantment_SlickOil),
        new ItemPickup(267, "Slippy Coating Oil", ItemIds.Enchantment_SlippyCoatingOil),
        new ItemPickup(268, "Slotmachine Oil", ItemIds.Enchantment_SlotmachineOil),
        new ItemPickup(269, "Slow Mo Oil", ItemIds.Enchantment_SlowMoOil),
        new ItemPickup(270, "Slow Punch Oil", ItemIds.Enchantment_SlowPunchOil),
        new ItemPickup(271, "Scroll of Slush", ItemIds.Enchantment_Slush),
        new ItemPickup(272, "Smart Bullet Oil", ItemIds.Enchantment_SmartBulletOil),
        new ItemPickup(273, "Smash Oil", ItemIds.Enchantment_SmashOil),
        new ItemPickup(274, "Soft Bullet Oil", ItemIds.Enchantment_SoftBulletOil),
        new ItemPickup(275, "Solid Oil", ItemIds.Enchantment_SolidOil),
        new ItemPickup(276, "Spartan Oil", ItemIds.Enchantment_SpartanOil),
        new ItemPickup(277, "Speed Trade Oil", ItemIds.Enchantment_SpeedTradeOil),
        new ItemPickup(278, "Spitter Oil", ItemIds.Enchantment_SpitterOil),
        new ItemPickup(279, "Spread Oil", ItemIds.Enchantment_SpreadOil),
        new ItemPickup(280, "Stability Oil", ItemIds.Enchantment_StabilityOil),
        new ItemPickup(281, "Stable Hip Oil", ItemIds.Enchantment_StableHipOil),
        new ItemPickup(282, "Stationary Oil", ItemIds.Enchantment_StationaryOil),
        new ItemPickup(283, "Scroll of Steam", ItemIds.Enchantment_Steam),
        new ItemPickup(284, "Stiffy Fit Oil", ItemIds.Enchantment_StiffyFitOil),
        new ItemPickup(285, "Stoic Oil", ItemIds.Enchantment_StoicOil),
        new ItemPickup(286, "Scroll of Storm Surge", ItemIds.Enchantment_StormSurge),
        new ItemPickup(287, "Suppressive Oil", ItemIds.Enchantment_SupressiveOil),
        new ItemPickup(288, "Surgical Laser Oil", ItemIds.Enchantment_SurgicalLaserOil),
        new ItemPickup(289, "Synchronicity Oil", ItemIds.Enchantment_SynchronicityOil),
        new ItemPickup(290, "Tactical Oil", ItemIds.Enchantment_TacticalOil),
        new ItemPickup(291, "Tandem Oil", ItemIds.Enchantment_TandemOil),
        new ItemPickup(292, "Task Oil", ItemIds.Enchantment_TaskOil),
        new ItemPickup(293, "Tech Support Oil", ItemIds.Enchantment_TechSupportOil),
        new ItemPickup(294, "Tension Oil", ItemIds.Enchantment_TensionOil),
        new ItemPickup(295, "Terminator Oil", ItemIds.Enchantment_TerminatorOil),
        new ItemPickup(296, "Test oil", ItemIds.Enchantment_TestOil),
        new ItemPickup(297, "Test oil 2", ItemIds.Enchantment_TestOil2),
        new ItemPickup(298, "Tetrus Oil", ItemIds.Enchantment_TetrisOil),
        new ItemPickup(299, "Thorough Oil", ItemIds.Enchantment_ThoroughOil),
        new ItemPickup(300, "Scroll of Thunderbolt", ItemIds.Enchantment_Thunderbolt),
        new ItemPickup(301, "Tight Barrel Oil", ItemIds.Enchantment_TightBarrelOil),
        new ItemPickup(302, "Tight Oil", ItemIds.Enchantment_TightOil),
        new ItemPickup(303, "Too Much Oil", ItemIds.Enchantment_TooMuchOil),
        new ItemPickup(304, "Scroll of Toxic Lobotomy", ItemIds.Enchantment_ToxicLobotomy),
        new ItemPickup(305, "Triple Oil", ItemIds.Enchantment_Trinity),
        new ItemPickup(306, "Trusty Old Oil", ItemIds.Enchantment_TrustyOldOil),
        new ItemPickup(307, "Turbulence Oil", ItemIds.Enchantment_TurbulenceOil),
        new ItemPickup(308, "Twice Oil", ItemIds.Enchantment_TwiceOil),
        new ItemPickup(309, "Two Time Oil", ItemIds.Enchantment_TwoTimeOil),
        new ItemPickup(310, "Unlabeled Oil", ItemIds.Enchantment_UnlabeledOil),
        new ItemPickup(311, "Untechnical Oil", ItemIds.Enchantment_UntechnicalOil),
        new ItemPickup(312, "Vasectomy Oil", ItemIds.Enchantment_VasectomyOil),
        new ItemPickup(313, "Vegan Oil", ItemIds.Enchantment_VeganOil),
        new ItemPickup(314, "Vegetable Oil", ItemIds.Enchantment_VegetableOil),
        new ItemPickup(315, "Velocity Oil", ItemIds.Enchantment_VelocityOil),
        new ItemPickup(316, "Scroll of Voodoo", ItemIds.Enchantment_Voodoo),
        new ItemPickup(317, "Walk Easy Oil", ItemIds.Enchantment_WalkEasyOil),
        new ItemPickup(318, "Waster Oil", ItemIds.Enchantment_WasterOil),
        new ItemScroll(319, "Scroll of Water", ItemIds.Enchantment_Water),
        new ItemPickup(320, "Whim Oil", ItemIds.Enchantment_WhimOil),
        new ItemPickup(321, "Whos Counting Oil", ItemIds.Enchantment_WhosCountingOil),
        new ItemPickup(322, "Wobble Oil", ItemIds.Enchantment_WobbleOil),
        new ItemPickup(323, "Xanny Oil", ItemIds.Enchantment_XanaxOil),
        new ItemPickup(324, "Zero Fucks Oil", ItemIds.Enchantment_ZeroFucksOil),
        new ItemPickup(325, "Zooming Oil", ItemIds.Enchantment_ZoomingOil),
        new ItemPickup(326, "Sulf Air", ItemIds.Item_AirBat),
        new ItemPickup(327, "Air Duster", ItemIds.Item_AirDuster),
        new ItemPickup(328, "Americano", ItemIds.Item_Americano),
        new ItemPickup(329, "Amulet", ItemIds.Item_Amulet),
        new ItemPickup(330, "Aspic", ItemIds.Item_Aspic),
        new ItemPickup(331, "Ass Wheel™", ItemIds.Item_AssWheel),
        new ItemPickup(332, "Badass Vest", ItemIds.Item_BadassVest),
        new ItemPickup(333, "Balaclava", ItemIds.Item_Balaklava),
        new ItemPickup(334, "Ballistic Helmet", ItemIds.Item_BallisticHelmet),
        new ItemPickup(335, "Ballistic Vest", ItemIds.Item_BallisticVest),
        new ItemPickup(336, "Banana", ItemIds.Item_Banana),
        new ItemPickup(337, "Banana Bread", ItemIds.Item_BananaBread),
        new ItemPickup(338, "Banana peel", ItemIds.Item_BananaPeel),
        new ItemPickup(339, "Banana Sulfs", ItemIds.Item_BananaSulfs),
        new ItemPickup(340, "Blue Bandana", ItemIds.Item_BandanaBlue),
        new ItemPickup(341, "Red Bandana", ItemIds.Item_BandanaRed),
        new ItemPickup(342, "Bark", ItemIds.Item_Bark),
        new ItemPickup(343, "Bark bread", ItemIds.Item_BarkBread),
        new ItemPickup(344, "Bathrobe", ItemIds.Item_Bathrobe),
        new ItemPickup(345, "Beanie", ItemIds.Item_Beanie),
        new ItemPickup(346, "Beans", ItemIds.Item_Beans),
        new ItemPickup(347, "Beef Jerky", ItemIds.Item_BeefJerky),
        new ItemPickup(348, "Beer Helmet", ItemIds.Item_BeerHelmet),
        new ItemPickup(349, "BeGone", ItemIds.Item_BeGone),
        new ItemPickup(350, "Berries", ItemIds.Item_Berries),
        new ItemPickup(351, "Biscuits and Gravy", ItemIds.Item_BiscuitsAndGravy),
        new ItemPickup(352, "Black Pepper", ItemIds.Item_BlackPepper),
        new ItemPickup(353, "Bladder", ItemIds.Item_Bladder),
        new ItemPickup(354, "Blast Boot", ItemIds.Item_BlastBoot),
        new ItemPickup(355, "Bleach", ItemIds.Item_Bleach),
        new ItemPickup(356, "Blindfold", ItemIds.Item_Blindfold),
        new ItemPickup(357, "Blood", ItemIds.Item_Blood),
        new ItemPickup(358, "Blood Bag", ItemIds.Item_BloodBag),
        new ItemPickup(359, "Fried Blood Pudding", ItemIds.Item_BloodPudding),
        new ItemPickup(360, "Blue Slipper", ItemIds.Item_BlueSlipper),
        new ItemPickup(361, "Boba Tea", ItemIds.Item_BobaTea),
        new ItemPickup(362, "Bomb", ItemIds.Item_Bomb),
        new ItemPickup(363, "Bone", ItemIds.Item_Bone),
        new ItemPickup(364, "Boomerang", ItemIds.Item_Boomerang),
        new ItemPickup(365, "BOOMerang", ItemIds.Item_Boomerang2),
        new ItemPickup(366, "Bottle", ItemIds.Item_Bottle),
        new ItemPickup(367, "Bottled Scream", ItemIds.Item_BottledScream),
        new ItemPickup(368, "Bottled Water", ItemIds.Item_BottledWater),
        new ItemPickup(369, "Brain", ItemIds.Item_Brain),
        new ItemPickup(370, "Bread", ItemIds.Item_Bread),
        new ItemPickup(371, "Breastplate", ItemIds.Item_Breastplate),
        new ItemPickup(372, "Broth", ItemIds.Item_Broth),
        new ItemPickup(373, "Butter", ItemIds.Item_Butter),
        new ItemPickup(374, "Buttermilk Pancakes", ItemIds.Item_ButtermilkPancakes),
        new ItemPickup(375, "Cacao", ItemIds.Item_Cacao),
        new ItemPickup(376, "Cactus", ItemIds.Item_Cactus),
        new ItemPickup(377, "Cactus Softdrink", ItemIds.Item_CactusDrink),
        new ItemPickup(378, "Grilled Cactus", ItemIds.Item_CactusGrilled),
        new ItemPickup(379, "Lackerol Cactus", ItemIds.Item_CactusSweets),
        new ItemPickup(380, "Caltrops", ItemIds.Item_Caltrops),
        new ItemPickup(381, "Camo Jacket", ItemIds.Item_CamoJacket),
        new ItemPickup(382, "Candy Cane", ItemIds.Item_CandyCane),
        new ItemPickup(383, "Cap", ItemIds.Item_Cap),
        new ItemPickup(384, "Cappuccino", ItemIds.Item_Cappuccino),
        new ItemPickup(385, "Bottled Caviar", ItemIds.Item_CaviarBottle),
        new ItemPickup(386, "Tube Caviar", ItemIds.Item_CaviarTubed),
        new ItemPickup(387, "Cencer", ItemIds.Item_Cencer),
        new ItemPickup(388, "Cereal", ItemIds.Item_Cereal),
        new ItemPickup(389, "Cevapi", ItemIds.Item_Cevapi),
        new ItemPickup(390, "Cheese", ItemIds.Item_Cheese),
        new ItemPickup(391, "Cheeseburger", ItemIds.Item_Cheeseburger),
        new ItemPickup(392, "Cheese Tops", ItemIds.Item_CheeseTops),
        new ItemPickup(393, "Chest of Drawers", ItemIds.Item_ChestOfDrawers),
        new ItemPickup(394, "Chicken Leg", ItemIds.Item_ChickenLeg),
        new ItemPickup(395, "Nashville Hot Chicken", ItemIds.Item_ChickenNashvilleHot),
        new ItemPickup(396, "Chocolate Ball", ItemIds.Item_ChocolateBall),
        new ItemPickup(397, "Chocolate Bar", ItemIds.Item_ChocolateBar),
        new ItemPickup(398, "Chocolate Syrup", ItemIds.Item_ChocolateSyrup),
        new ItemPickup(399, "Christmas Sock", ItemIds.Item_ChristmasSock),
        new ItemPickup(400, "Christmas Spice", ItemIds.Item_ChristmasSpice),
        new ItemPickup(401, "Christmas Sweater", ItemIds.Item_ChristmasSweater),
        new ItemPickup(402, "Father's Shirt", ItemIds.Item_ClergyCollar),
        new ItemPickup(403, "Climbing Gear", ItemIds.Item_ClimbingGear),
        new ItemPickup(404, "Clog", ItemIds.Item_Clog),
        new ItemPickup(405, "Cloth", ItemIds.Item_Cloth),
        new ItemPickup(406, "Coffee", ItemIds.Item_Coffee),
        new ItemPickup(407, "Combat Boot", ItemIds.Item_CombatBoots),
        new ItemPickup(408, "Cordon Bleu", ItemIds.Item_CordonBleu),
        new ItemPickup(409, "Cotton Candy", ItemIds.Item_CottonCandy),
        new ItemPickup(410, "Cotton Swabs", ItemIds.Item_CottonSwab),
        new ItemPickup(411, "Cowboy Boot", ItemIds.Item_CowboyBoot),
        new ItemPickup(412, "Cowboy Hat", ItemIds.Item_CowboyHat),
        new ItemPickup(413, "Cowboy Vest", ItemIds.Item_CowboyVest),
        new ItemPickup(414, "Craw Eye", ItemIds.Item_CrawEye),
        new ItemPickup(415, "Craw Flesh", ItemIds.Item_CrawFlesh),
        new ItemPickup(416, "Craw Skin", ItemIds.Item_CrawSkin),
        new ItemPickup(417, "Crown", ItemIds.Item_Crown),
        new ItemPickup(418, "Crypt Key", ItemIds.Item_CryptKey),
        new ItemPickup(419, "Cuisses De Grenouille", ItemIds.Item_CuissesDeGrenouille),
        new ItemPickup(420, "Cultist Heart", ItemIds.Item_CultistHeart),
        new ItemPickup(421, "Curry", ItemIds.Item_Curry),
        new ItemPickup(422, "Currywurst", ItemIds.Item_Currywurst),
        new ItemPickup(423, "Dark Lamp", ItemIds.Item_Darklamp),
        new ItemPickup(424, "Death's Favor", ItemIds.Item_DeathsFavor),
        new ItemPickup(425, "Denim Jacket", ItemIds.Item_DenimJacket),
        new ItemPickup(426, "Detective Pipe", ItemIds.Item_DetectivePipe),
        new ItemPickup(427, "Dimmie", ItemIds.Item_Dimmie),
        new ItemPickup(428, "Disgusting Cookbook", ItemIds.Item_DisgustingCookbook),
        new ItemPickup(429, "Dish Soap", ItemIds.Item_DishSoap),
        new ItemPickup(430, "Diving Mask", ItemIds.Item_DivingMask),
        new ItemPickup(431, "Dog Eye", ItemIds.Item_DogEye),
        new ItemPickup(432, "Dog Flesh", ItemIds.Item_DogFlesh),
        new ItemPickup(433, "Dog Skin", ItemIds.Item_DogSkin),
        new ItemPickup(434, "Dogtags", ItemIds.Item_Dogtags),
        new ItemPickup(435, "Dog Whistle", ItemIds.Item_DogWhistle),
        new ItemPickup(436, "Dopp i Grytan", ItemIds.Item_DoppIGrytan),
        new ItemPickup(437, "Double Cheeseburger", ItemIds.Item_DoubleCheeseburger),
        new ItemPickup(438, "Dunce Cap", ItemIds.Item_DunceCap),
        new ItemPickup(439, "Ear Protectors", ItemIds.Item_EarProtectors),
        new ItemPickup(440, "Egg", ItemIds.Item_Egg),
        new ItemPickup(441, "Egg Toddy", ItemIds.Item_EggToddy),
        new ItemPickup(442, "Encrypted Hoodie", ItemIds.Item_EncryptedHoodie),
        new ItemPickup(443, "Energy Gum", ItemIds.Item_EnergyGum),
        new ItemPickup(444, "Escargot", ItemIds.Item_Escargot),
        new ItemPickup(445, "Extra Lung", ItemIds.Item_ExtraLung),
        new ItemPickup(446, "Eye Patch", ItemIds.Item_EyePatch),
        new ItemPickup(447, "False Sulfcap", ItemIds.Item_FalseSulfcap),
        new ItemPickup(448, "Fatberg Chunk", ItemIds.Item_FatbergChunk),
        new ItemPickup(449, "Firefighter Helmet", ItemIds.Item_FirefighterHelmet),
        new ItemPickup(450, "Firefighter Jacket", ItemIds.Item_FirefighterJacket),
        new ItemPickup(451, "First Aid Kit", ItemIds.Item_FirstAidKit),
        new ItemPickup(452, "Fish", ItemIds.Item_Fish),
        new ItemPickup(453, "Fishing Rod", ItemIds.Item_FishingRod),
        new ItemPickup(454, "Fish and chips", ItemIds.Item_FishNChips),
        new ItemPickup(455, "Salted Fish", ItemIds.Item_FishSalted),
        new ItemPickup(456, "Flour", ItemIds.Item_Flour),
        new ItemPickup(457, "Fluffy Hat", ItemIds.Item_FluffyHat),
        new ItemPickup(458, "Fondue", ItemIds.Item_Fondue),
        new ItemPickup(459, "Four-leaf Clover", ItemIds.Item_FourLeafClover),
        new ItemPickup(460, "French Hotdog", ItemIds.Item_FrenchHotdog),
        new ItemPickup(461, "French Toast", ItemIds.Item_FrenchToast),
        new ItemPickup(462, "Frog Leg", ItemIds.Item_FrogLeg),
        new ItemPickup(463, "Diving Fin", ItemIds.Item_FrogmanFoot),
        new ItemPickup(464, "Full English Breakfast", ItemIds.Item_FullEnglishBreakfast),
        new ItemPickup(465, "Funny Gas", ItemIds.Item_FunnyGas),
        new ItemPickup(466, "Gas Mask", ItemIds.Item_GasMask),
        new ItemPickup(467, "Genie Shoe", ItemIds.Item_GenieShoe),
        new ItemPickup(468, "Geta", ItemIds.Item_Geta),
        new ItemPickup(469, "Ghillie Suit", ItemIds.Item_GhillieSuit),
        new ItemPickup(470, "Goblin eye", ItemIds.Item_GoblinEye),
        new ItemPickup(471, "Goblin flesh", ItemIds.Item_GoblinFlesh),
        new ItemPickup(472, "Goblin skin", ItemIds.Item_GoblinSkin),
        new ItemPickup(473, "Golden Slipper", ItemIds.Item_GoldenSlipper),
        new ItemPickup(474, "Gonster", ItemIds.Item_Gonster),
        new ItemPickup(475, "Graved salmon", ItemIds.Item_GravadLax),
        new ItemPickup(476, "Gravy", ItemIds.Item_Gravy),
        new ItemPickup(477, "Green Glob", ItemIds.Item_GreenGlob),
        new ItemPickup(478, "Grilled Poultry", ItemIds.Item_GrilledPoultry),
        new ItemPickup(479, "Sweet Gum", ItemIds.Item_GumHubba),
        new ItemPickup(480, "Haggis", ItemIds.Item_Haggis),
        new ItemPickup(481, "Hard Bread", ItemIds.Item_HardBread),
        new ItemPickup(482, "Hardhat", ItemIds.Item_HardHat),
        new ItemPickup(483, "Hardshell Taco", ItemIds.Item_HardshellTaco),
        new ItemPickup(485, "Hazelnut", ItemIds.Item_Hazelnut),
        new ItemPickup(486, "Hazmat Suit", ItemIds.Item_HazmatSuit),
        new ItemPickup(487, "Health Potion", ItemIds.Item_HealthPotion),
        new ItemPickup(488, "Heart", ItemIds.Item_Heart),
        new ItemPickup(489, "Hedgehog Suit", ItemIds.Item_HedgehogSuit),
        new ItemPickup(490, "Herbs", ItemIds.Item_Herb),
        new ItemPickup(491, "Herbal Tea", ItemIds.Item_HerbalTea),
        new ItemPickup(492, "High Heel", ItemIds.Item_HighHeel),
        new ItemPickup(493, "High Quality Elf Shoe", ItemIds.Item_HighQualityElfShoe),
        new ItemPickup(494, "Hockey Shoulder Pads", ItemIds.Item_HockeyArmor),
        new ItemPickup(495, "Hockey Helmet", ItemIds.Item_HockeyHelmet),
        new ItemPickup(496, "Holy Toast", ItemIds.Item_HolyToast),
        new ItemPickup(497, "Holy Water", ItemIds.Item_HolyWater),
        new ItemPickup(498, "Holy Water (Unused)", ItemIds.Item_HolyWater_Old),
        new ItemPickup(499, "Yellow Hoodie", ItemIds.Item_HoodieSklett),
        new ItemPickup(500, "Hot Pot", ItemIds.Item_HotPot),
        new ItemPickup(501, "Hot Sauce", ItemIds.Item_HotSauce),
        new ItemPickup(502, "Hot Snacks", ItemIds.Item_HotSnax),
        new ItemPickup(503, "Human eye", ItemIds.Item_HumanEye),
        new ItemPickup(504, "Human flesh", ItemIds.Item_HumanFlesh),
        new ItemPickup(505, "Human skin", ItemIds.Item_HumanSkin),
        new ItemPickup(506, "Hunting Vest", ItemIds.Item_HuntingVest),
        new ItemPickup(507, "Ice Skate", ItemIds.Item_IceSkate),
        new ItemPickup(508, "Instant Defibrillator", ItemIds.Item_InstantDefibrilator),
        new ItemPickup(509, "Intestines", ItemIds.Item_Intestines),
        new ItemPickup(510, "Iron Feather", ItemIds.Item_IronFeather),
        new ItemPickup(511, "Berry Jam", ItemIds.Item_Jam),
        new ItemPickup(512, "Berry Jam (Unsweetened)", ItemIds.Item_JamUnsweetened),
        new ItemPickup(513, "Jansson's Temptation", ItemIds.Item_JanssonsTemptation),
        new ItemPickup(514, "Jello", ItemIds.Item_Jello),
        new ItemPickup(515, "Jet Pack", ItemIds.Item_Jetpack),
        new ItemPickup(516, "Julmust", ItemIds.Item_Julmust),
        new ItemPickup(517, "Juniper Branch", ItemIds.Item_JuniperBranch),
        new ItemPickup(518, "Karl-Oskar", ItemIds.Item_KarlOskar),
        new ItemPickup(519, "Kidney", ItemIds.Item_Kidney),
        new ItemPickup(520, "Kidney Pie", ItemIds.Item_KidneyPie),
        new ItemPickup(521, "Kidney Stone", ItemIds.Item_KidneyStone),
        new ItemPickup(522, "Knee Pads", ItemIds.Item_KneePads),
        new ItemPickup(523, "Knight's Helmet", ItemIds.Item_KnightsHelmet),
        new ItemPickup(524, "Kombucha", ItemIds.Item_Kombucha),
        new ItemPickup(525, "Latte", ItemIds.Item_Latte),
        new ItemPickup(526, "Leather Jacket", ItemIds.Item_LeatherJacket),
        new ItemPickup(527, "Lemonade", ItemIds.Item_Lemonade),
        new ItemPickup(528, "Leverpastej", ItemIds.Item_Leverpastej),
        new ItemPickup(529, "Library Card", ItemIds.Item_LibraryCard),
        new ItemPickup(530, "Life Vest", ItemIds.Item_LifeVest),
        new ItemPickup(531, "Lightning in a Bottle", ItemIds.Item_LightningInABottle),
        new ItemPickup(532, "Liquor", ItemIds.Item_Liquor),
        new ItemPickup(533, "Liver", ItemIds.Item_Liver),
        new ItemPickup(534, "Dumpling", ItemIds.Item_LiverDumpling),
        new ItemPickup(535, "Shav'Wa bladder", ItemIds.Item_LizardBladder),
        new ItemPickup(536, "Shav'Wa eye", ItemIds.Item_LizardEye),
        new ItemPickup(537, "Shav'Wa flesh", ItemIds.Item_LizardFlesh),
        new ItemPickup(538, "Shav'Wa skin", ItemIds.Item_LizardSkin),
        new ItemPickup(539, "Loaded Die", ItemIds.Item_LoadedDice),
        new ItemPickup(540, "Lock of the Magus", ItemIds.Item_LockOfTheMagus),
        new ItemPickup(541, "Lung", ItemIds.Item_Lung),
        new ItemPickup(542, "Lussekatt", ItemIds.Item_Lussekatt),
        new ItemPickup(543, "Lutfisk", ItemIds.Item_Lutfisk),
        new ItemPickup(544, "Mac'n'Cheese", ItemIds.Item_MacNCheese),
        new ItemPickup(545, "Maki", ItemIds.Item_Maki),
        new ItemPickup(546, "Marshmallows", ItemIds.Item_Marshmallow),
        new ItemPickup(547, "Mashed Potatoes", ItemIds.Item_MashedPotatoes),
        new ItemPickup(548, "Green Tea Gum", ItemIds.Item_MatchaGum),
        new ItemPickup(549, "Green Tea", ItemIds.Item_MatchaTeaCup),
        new ItemPickup(550, "Matcha", ItemIds.Item_MatchaTeaPowder),
        new ItemPickup(551, "Meat Skewer", ItemIds.Item_MeatSkewers),
        new ItemPickup(552, "Meringue", ItemIds.Item_Meringue),
        new ItemPickup(553, "Metabulator Pump", ItemIds.Item_MetabulatorPump),
        new ItemPickup(554, "Metal Detector", ItemIds.Item_MetalDetector),
        new ItemPickup(555, "Metal Scrap", ItemIds.Item_MetalScrap),
        new ItemPickup(556, "Microfiber Dish Cloth", ItemIds.Item_MicrofiberDishCloth),
        new ItemPickup(557, "High Cut Helmet", ItemIds.Item_MilitaryHelmet),
        new ItemPickup(558, "Skimmed Milk", ItemIds.Item_MilkBlue),
        new ItemPickup(559, "Buttermilk", ItemIds.Item_MilkButtermilk),
        new ItemPickup(560, "Low Fat Milk", ItemIds.Item_MilkGreen),
        new ItemPickup(561, "Whole Milk", ItemIds.Item_MilkRed),
        new ItemPickup(562, "Berry Milkshake", ItemIds.Item_MilkshakeBerries),
        new ItemPickup(563, "Chocolate Milkshake", ItemIds.Item_MilkshakeChocolate),
        new ItemPickup(564, "Mineral Water", ItemIds.Item_MineralWater),
        new ItemPickup(565, "Mochi", ItemIds.Item_Mochi),
        new ItemPickup(566, "Monkey Paw", ItemIds.Item_MonkeyPaw),
        new ItemPickup(567, "Motorcycle Helmet", ItemIds.Item_MotorcycleHelmet),
        new ItemPickup(568, "Chocolate Mudcake", ItemIds.Item_Mudcake),
        new ItemPickup(569, "Mulled Wine", ItemIds.Item_MulledWine),
        new ItemPickup(570, "Fried Mushroom", ItemIds.Item_MushroomFried),
        new ItemPickup(571, "Mushroom Omelette", ItemIds.Item_MushroomOmelette),
        new ItemPickup(572, "Mushroom Skewer", ItemIds.Item_MushroomSkewer),
        new ItemPickup(573, "Mushroom Soup", ItemIds.Item_MushroomSoup),
        new ItemPickup(574, "Mutagen Capsule", ItemIds.Item_Mutagen),
        new ItemPickup(575, "Mycota Squamata", ItemIds.Item_MycotaSquamata),
        new ItemPickup(576, "Mystery Meat", ItemIds.Item_MysteryMeat),
        new ItemPickup(577, "Nigiri", ItemIds.Item_Nigiri),
        new ItemPickup(578, "Nuggets", ItemIds.Item_Nuggets),
        new ItemPickup(579, "Nut Mix", ItemIds.Item_NutMix),
        new ItemPickup(580, "Nut Spread", ItemIds.Item_NutSpread),
        new ItemPickup(581, "Oats", ItemIds.Item_Oats),
        new ItemPickup(582, "Office Wear", ItemIds.Item_OfficeShirt),
        new ItemPickup(583, "Oil Lamp", ItemIds.Item_OilLamp),
        new ItemPickup(584, "Old-Timey Suit", ItemIds.Item_OldTimeySuit),
        new ItemPickup(585, "Omelette", ItemIds.Item_Omelette),
        new ItemPickup(586, "Onigiri", ItemIds.Item_Onigiri),
        new ItemPickup(587, "Pancreas", ItemIds.Item_Pancreas),
        new ItemPickup(588, "Paper", ItemIds.Item_Paper),
        new ItemPickup(589, "Parka", ItemIds.Item_Parka),
        new ItemPickup(590, "Spaghetti Bolognese", ItemIds.Item_PastaBolognese),
        new ItemPickup(591, "Peanut", ItemIds.Item_Peanut),
        new ItemPickup(592, "Peanut Butter", ItemIds.Item_PeanutButter),
        new ItemPickup(593, "Peg Leg", ItemIds.Item_PegLeg),
        new ItemPickup(594, "Pillow Armor", ItemIds.Item_PillowArmor),
        new ItemPickup(595, "Pine nuts", ItemIds.Item_PineNut),
        new ItemPickup(596, "Pith Helmet", ItemIds.Item_PithHelmet),
        new ItemPickup(597, "Pizza", ItemIds.Item_PizzaLarge),
        new ItemPickup(598, "Pizza Slice", ItemIds.Item_PizzaSlice),
        new ItemPickup(599, "Plain White Tee", ItemIds.Item_PlainWhiteTee),
        new ItemPickup(600, "Plate Carrier", ItemIds.Item_PlateCarrier),
        new ItemPickup(601, "Platform Shoe", ItemIds.Item_PlatformShoe),
        new ItemPickup(602, "Pocket Sand", ItemIds.Item_PocketSand),
        new ItemPickup(603, "Anti-Poison Gum", ItemIds.Item_PoisonGum),
        new ItemPickup(604, "Police Hat", ItemIds.Item_PoliceHat),
        new ItemPickup(605, "Police Uniform", ItemIds.Item_PoliceUniform),
        new ItemPickup(606, "Pölsa", ItemIds.Item_Polsa),
        new ItemPickup(607, "Pølse", ItemIds.Item_Polse),
        new ItemPickup(608, "Pope Hat", ItemIds.Item_PopeHat),
        new ItemPickup(609, "Porridge", ItemIds.Item_Porridge),
        new ItemPickup(610, "Potato", ItemIds.Item_Potato),
        new ItemPickup(611, "Potato Salad", ItemIds.Item_PotatoSalad),
        new ItemPickup(612, "Poutine", ItemIds.Item_Poutine),
        new ItemPickup(613, "Power Bar", ItemIds.Item_PowerBar),
        new ItemPickup(615, "Pyjamas", ItemIds.Item_Pyjama),
        new ItemPickup(616, "Pyttipanna", ItemIds.Item_PyttIPanna),
        new ItemPickup(617, "Raclette", ItemIds.Item_Raclette),
        new ItemPickup(618, "Raincoat", ItemIds.Item_Raincoat),
        new ItemPickup(619, "Ramen", ItemIds.Item_Ramen),
        new ItemPickup(620, "Tori Ramen", ItemIds.Item_RamenTori),
        new ItemPickup(622, "Range Finder", ItemIds.Item_RangeFinder),
        new ItemPickup(623, "Rat Cage", ItemIds.Item_RatCage),
        new ItemPickup(624, "Razorang", ItemIds.Item_Razorang),
        new ItemPickup(625, "Razor Blossom", ItemIds.Item_RazorBlossom),
        new ItemPickup(626, "Refrigerator", ItemIds.Item_Refrigerator),
        new ItemPickup(627, "Rhubarb", ItemIds.Item_Rhubarb),
        new ItemPickup(628, "Rhubarb Pie", ItemIds.Item_RhubarbPie),
        new ItemPickup(629, "Rhubarb Porridge", ItemIds.Item_RhubarbPorridge),
        new ItemPickup(630, "Rhubarb Sauce", ItemIds.Item_RhubarbSauce),
        new ItemPickup(631, "Rice", ItemIds.Item_Rice),
        new ItemPickup(632, "Puffed Rice Cakes", ItemIds.Item_RiceCake),
        new ItemPickup(633, "Risalamande", ItemIds.Item_Risalamalta),
        new ItemPickup(634, "Rice Porridge", ItemIds.Item_Risgrynsgrot),
        new ItemPickup(635, "Robot Brain", ItemIds.Item_RobotBrain),
        new ItemPickup(636, "Robot Control Unit", ItemIds.Item_RobotControlUnit),
        new ItemPickup(637, "Robot Eye", ItemIds.Item_RobotEye),
        new ItemPickup(638, "Robot Flesh", ItemIds.Item_RobotFlesh),
        new ItemPickup(639, "Robot Heart", ItemIds.Item_RobotHeart),
        new ItemPickup(640, "Robot Hydraul", ItemIds.Item_RobotHydraul),
        new ItemPickup(641, "Robot Joint Pneumatic", ItemIds.Item_RobotJoint),
        new ItemPickup(642, "Robot Plate", ItemIds.Item_RobotPlate),
        new ItemPickup(643, "Robot Septacoil", ItemIds.Item_RobotSeptacoil),
        new ItemPickup(644, "Robot Soul Capsule", ItemIds.Item_RobotSoulCapsule),
        new ItemPickup(645, "Rock", ItemIds.Item_Rock),
        new ItemPickup(646, "Rödsopp", ItemIds.Item_Rodsopp),
        new ItemPickup(647, "Rödsopp Paste", ItemIds.Item_RodsoppPaste),
        new ItemPickup(648, "Roller Blade", ItemIds.Item_Rollerblade),
        new ItemPickup(649, "Round Glasses", ItemIds.Item_RoundGlasses),
        new ItemPickup(650, "Rubber", ItemIds.Item_Rubber),
        new ItemPickup(651, "Rubber Boot", ItemIds.Item_RubberBoot),
        new ItemPickup(652, "Rudolf Nose", ItemIds.Item_RudolfNose),
        new ItemPickup(653, "Running Shoe", ItemIds.Item_RunningShoes),
        new ItemPickup(654, "Safe", ItemIds.Item_Safe),
        new ItemPickup(655, "Safety Vest", ItemIds.Item_SafetyVest),
        new ItemPickup(656, "Salt", ItemIds.Item_Salt),
        new ItemPickup(657, "Salted Sandfish", ItemIds.Item_SaltedSandfish),
        new ItemPickup(658, "Samurai Armor", ItemIds.Item_SamuraiArmor),
        new ItemPickup(659, "Flat Sandfish", ItemIds.Item_SandFish),
        new ItemPickup(660, "Bread Sandwich", ItemIds.Item_SandwichBread),
        new ItemPickup(661, "Buddy Sandwich", ItemIds.Item_SandwichBuddy),
        new ItemPickup(662, "Butter Sandwich", ItemIds.Item_SandwichButter),
        new ItemPickup(663, "Cheese Sandwich", ItemIds.Item_SandwichCheese),
        new ItemPickup(664, "Liver Pâté Sandwich", ItemIds.Item_SandwichLeverpastej),
        new ItemPickup(665, "Nut Spread Sandwich", ItemIds.Item_SandwichNutSpread),
        new ItemPickup(666, "Peanutbutter Sandwich", ItemIds.Item_SandwichPeanutbutter),
        new ItemPickup(667, "Peanutbutter Jelly Sandwich", ItemIds.Item_SandwichPeanutbutterJelly),
        new ItemPickup(668, "Santa Coat", ItemIds.Item_SantaCoat),
        new ItemPickup(669, "Santa Hat", ItemIds.Item_SantaHat),
        new ItemPickup(670, "Sashimi", ItemIds.Item_Sashimi),
        new ItemPickup(671, "Spicy Sausage", ItemIds.Item_Sausage),
        new ItemPickup(672, "Sausage Omelette", ItemIds.Item_SausageOmelette),
        new ItemPickup(673, "Sausage On Stick", ItemIds.Item_SausageOnStick),
        new ItemPickup(674, "Sausage Soup", ItemIds.Item_SausageSoup),
        new ItemPickup(675, "Sawdust", ItemIds.Item_Sawdust),
        new ItemPickup(676, "Oxygen Tank", ItemIds.Item_ScubaTank),
        new ItemPickup(677, "Seaweed", ItemIds.Item_Seaweed),
        new ItemPickup(678, "Sheriff's Badge", ItemIds.Item_SheriffBadge),
        new ItemPickup(679, "Shield Belt", ItemIds.Item_ShieldBelt),
        new ItemPickup(680, "Shoe", ItemIds.Item_Shoe),
        new ItemPickup(681, "Shovel", ItemIds.Item_Shovel),
        new ItemPickup(682, "Hellshrew eye", ItemIds.Item_ShrewEye),
        new ItemPickup(683, "Hellshrew flesh", ItemIds.Item_ShrewFlesh),
        new ItemPickup(684, "Hellshrew skin", ItemIds.Item_ShrewSkin),
        new ItemPickup(685, "Shrink Ray", ItemIds.Item_ShrinkRay),
        new ItemPickup(686, "Shurikens", ItemIds.Item_Shurikens),
        new ItemPickup(687, "Pickled herring platter", ItemIds.Item_Silltalrik),
        new ItemPickup(688, "Ski Goggles", ItemIds.Item_SkiGoggles),
        new ItemPickup(689, "Smoke Grenade", ItemIds.Item_SmokeGrenade),
        new ItemPickup(690, "Snail", ItemIds.Item_Snail),
        new ItemPickup(691, "Sneaker", ItemIds.Item_Sneaker),
        new ItemPickup(692, "Admiral White Extra Strong", ItemIds.Item_Snus),
        new ItemPickup(693, "Sock", ItemIds.Item_Sock),
        new ItemPickup(694, "Soda", ItemIds.Item_Soda),
        new ItemPickup(695, "Solution", ItemIds.Item_Solution),
        new ItemPickup(696, "Spaghetti", ItemIds.Item_Spagetti),
        new ItemPickup(697, "Spanish Omelette", ItemIds.Item_SpanishOmelette),
        new ItemPickup(698, "Spice Mix", ItemIds.Item_SpiceMix),
        new ItemPickup(699, "Spleen", ItemIds.Item_Spleen),
        new ItemPickup(700, "Sports Drink", ItemIds.Item_SportsDrink),
        new ItemPickup(701, "Springcoil Boot", ItemIds.Item_SpringCoilBoots),
        new ItemPickup(702, "Square Glasses", ItemIds.Item_SquareGlasses),
        new ItemPickup(703, "Steel Helmet", ItemIds.Item_SteelHelmet),
        new ItemPickup(704, "Stew", ItemIds.Item_Stew),
        new ItemPickup(705, "Stick", ItemIds.Item_Stick),
        new ItemPickup(706, "Stout", ItemIds.Item_Stout),
        new ItemPickup(707, "Straitjacket", ItemIds.Item_StraightJacket),
        new ItemPickup(708, "Sugar", ItemIds.Item_Sugar),
        new ItemPickup(709, "Suitcase", ItemIds.Item_Suitcase),
        new ItemPickup(710, "SULFUR Cap", ItemIds.Item_SulfurCap),
        new ItemPickup(711, "SULFUR Hoodie", ItemIds.Item_SulfurHoodie),
        new ItemPickup(712, "Sunglasses", ItemIds.Item_Sunglasses),
        new ItemPickup(713, "Surstromming", ItemIds.Item_Surstromming),
        new ItemPickup(714, "Suspensor Shield", ItemIds.Item_SuspensorShield),
        new ItemPickup(715, "Soapy Wool", ItemIds.Item_Svinto),
        new ItemPickup(716, "Swedish Pancakes", ItemIds.Item_SwedishPancakes),
        new ItemPickup(717, "Swing-Ding", ItemIds.Item_SwingDing),
        new ItemPickup(718, "Sylvester Hat", ItemIds.Item_SylvesterHat),
        new ItemPickup(719, "Tanker Helmet", ItemIds.Item_TankerHelmet),
        new ItemPickup(720, "Thyroid", ItemIds.Item_Thyroid),
        new ItemPickup(721, "Titanium Helmet", ItemIds.Item_TitaniumHelmet),
        new ItemPickup(722, "Toaster", ItemIds.Item_Toaster),
        new ItemPickup(723, "Toast Skagen", ItemIds.Item_ToastSkagen),
        new ItemPickup(724, "Tongue", ItemIds.Item_Tongue),
        new ItemPickup(725, "Tongue On Stick", ItemIds.Item_TongueOnStick),
        new ItemPickup(726, "Tracksuit", ItemIds.Item_Tracksuit),
        new ItemPickup(727, "Trapped Angel", ItemIds.Item_TrappedAngel),
        new ItemPickup(728, "Green Tunic", ItemIds.Item_Tunic),
        new ItemPickup(729, "Turtle Shell", ItemIds.Item_TurtleShell),
        new ItemPickup(730, "Unagi", ItemIds.Item_Unagi),
        new ItemPickup(731, "Used Rubber", ItemIds.Item_UsedRubber),
        new ItemPickup(732, "Vacuum Cleaner", ItemIds.Item_VacuumCleaner),
        new ItemPickup(734, "Velvet Bell", ItemIds.Item_VelvetBell),
        new ItemPickup(735, "Vibraport", ItemIds.Item_Vibraport),
        new ItemPickup(736, "Voodoo Doll", ItemIds.Item_VoodooDoll),
        new ItemPickup(737, "Walnut", ItemIds.Item_Walnut),
        new ItemPickup(738, "Wardrobe", ItemIds.Item_Wardrobe),
        new ItemPickup(739, "Weapon Rack 1", ItemIds.Item_WeaponRack0),
        new ItemPickup(740, "Weapon Rack 2", ItemIds.Item_WeaponRack1),
        new ItemPickup(741, "Repair Kit", ItemIds.Item_WeaponRepairKit),
        new ItemPickup(742, "Wet Wipes", ItemIds.Item_WetWipes),
        new ItemPickup(743, "Red Wine", ItemIds.Item_Wine),
        new ItemPickup(744, "Winter Scarf", ItemIds.Item_WinterScarf),
        new ItemPickup(745, "Wooden Armor", ItemIds.Item_WoodenArmor),
        new ItemPickup(747, "Earthworm", ItemIds.Item_Worm),
        new ItemPickup(748, "Yakety Sax", ItemIds.Item_YaketySax),
        new ItemPickup(749, "Ygg", ItemIds.Item_Ygg),
        new ItemPickup(750, "Guild Approved Cuisine", ItemIds.Manual_BlackGuildCooking),
        new ItemPickup(751, "The Chequered Cookbook", ItemIds.Manual_ChequeredCookbook),
        new ItemPickup(752, "Eating as Royals", ItemIds.Manual_CookingCastle),
        new ItemPickup(753, "From the Cellar", ItemIds.Manual_CookingDungeon),
        new ItemPickup(754, "Shav'Wani delights", ItemIds.Manual_CookingFortress),
        new ItemPickup(755, "Tastes From the Sewers™️", ItemIds.Manual_CookingSewers),
        new ItemPickup(756, "Food for Desert Survival", ItemIds.Manual_DesertCooking),
        new ItemPickup(757, "Delicacies of the Forest", ItemIds.Manual_ForestCooking),
        new ItemPickup(758, "GABBA FOODMAKE", ItemIds.Manual_GoblinCooking),
        new ItemPickup(759, "Recipe: Aspic", ItemIds.Manual_Recipe_Aspic_1),
        new ItemPickup(760, "Recipe: Banana Sulfs", ItemIds.Manual_Recipe_BananaSulfs),
        new ItemPickup(761, "Recipe: Bark bread", ItemIds.Manual_Recipe_BarkBread),
        new ItemPickup(762, "Recipe: Beef Jerky", ItemIds.Manual_Recipe_BeefJerky_5_3),
        new ItemPickup(763, "Recipe: Broth 1", ItemIds.Manual_Recipe_Broth_1),
        new ItemPickup(764, "Recipe: Broth 2", ItemIds.Manual_Recipe_Broth_3),
        new ItemPickup(765, "Recipe: Butter 1", ItemIds.Manual_Recipe_Butter_1),
        new ItemPickup(766, "Recipe: Butter 2", ItemIds.Manual_Recipe_Butter_2),
        new ItemPickup(767, "Recipe: Cheese", ItemIds.Manual_Recipe_Cheese_9),
        new ItemPickup(768, "Recipe: Cheeseburger", ItemIds.Manual_Recipe_Cheeseburger_1_2),
        new ItemPickup(769, "Recipe: Double Cheeseburger", ItemIds.Manual_Recipe_CheeseburgerDouble_1_2),
        new ItemPickup(770, "Recipe: Cheese Tops", ItemIds.Manual_Recipe_CheeseTops_1),
        new ItemPickup(771, "Recipe: Nuggets", ItemIds.Manual_Recipe_ChickenNuggets),
        new ItemPickup(772, "Recipe: Chocolate Ball", ItemIds.Manual_Recipe_ChocolateBall_1),
        new ItemPickup(773, "Recipe: Chocolate Syrup", ItemIds.Manual_Recipe_ChocolateSyrup_1),
        new ItemPickup(774, "Recipe: Cordon Bleu", ItemIds.Manual_Recipe_CordonBleu),
        new ItemPickup(775, "Recipe: Cuisses De Grenouille", ItemIds.Manual_Recipe_CuissesDeGrenouille_1),
        new ItemPickup(776, "Recipe: Currywurst", ItemIds.Manual_Recipe_CurryWurst_4),
        new ItemPickup(777, "Recipe: Vacuum Cleaner", ItemIds.Manual_Recipe_Dammsugare),
        new ItemPickup(778, "Recipe: Dimmie", ItemIds.Manual_Recipe_Dimmies),
        new ItemPickup(779, "Recipe: Egg Toddy", ItemIds.Manual_Recipe_EggToddy_1),
        new ItemPickup(780, "Recipe: Escargot", ItemIds.Manual_Recipe_Escargot_1),
        new ItemPickup(781, "Recipe: Extra Lung 1", ItemIds.Manual_Recipe_ExtraLung_1),
        new ItemPickup(782, "Recipe: Extra Lung 2", ItemIds.Manual_Recipe_ExtraLung_2),
        new ItemPickup(783, "Recipe: Fish and chips", ItemIds.Manual_Recipe_FishnChips_1),
        new ItemPickup(784, "Recipe: Fondue", ItemIds.Manual_Recipe_Fondue_1),
        new ItemPickup(785, "Recipe: French Hotdog", ItemIds.Manual_Recipe_FrenchHotdog_2),
        new ItemPickup(786, "Recipe: French Toast", ItemIds.Manual_Recipe_FrenchToast_1),
        new ItemPickup(787, "Recipe: Full English Breakfast 1", ItemIds.Manual_Recipe_FullEnglishBreakfast_1_1),
        new ItemPickup(788, "Recipe: Full English Breakfast 2", ItemIds.Manual_Recipe_FullEnglishBreakfast_1_2),
        new ItemPickup(789, "Recipe: Gonster", ItemIds.Manual_Recipe_Gonster),
        new ItemPickup(790, "Recipe: Green Glob 1", ItemIds.Manual_Recipe_GreenGlob),
        new ItemPickup(791, "Recipe: Green Glob 2", ItemIds.Manual_Recipe_GreenGlob_1),
        new ItemPickup(792, "Recipe: Sweet Gum 1", ItemIds.Manual_Recipe_Gum_2),
        new ItemPickup(793, "Recipe: Sweet Gum 2", ItemIds.Manual_Recipe_Gum_3),
        new ItemPickup(794, "Recipe: Hard Bread", ItemIds.Manual_Recipe_HardBread_1),
        new ItemPickup(795, "Recipe: Holy Toast", ItemIds.Manual_Recipe_HolyToast_1),
        new ItemPickup(796, "Recipe: Hot Pot 1", ItemIds.Manual_Recipe_Hotpot),
        new ItemPickup(797, "Recipe: Hot Pot 2", ItemIds.Manual_Recipe_Hotpot_2),
        new ItemPickup(798, "Recipe: Hot Pot 3", ItemIds.Manual_Recipe_Hotpot_3),
        new ItemPickup(799, "Recipe: Hot Pot 4", ItemIds.Manual_Recipe_Hotpot_4),
        new ItemPickup(800, "Recipe: Berry Jam", ItemIds.Manual_Recipe_Jam_1),
        new ItemPickup(801, "Recipe: Jello", ItemIds.Manual_Recipe_Jello_1),
        new ItemPickup(802, "Recipe: Kidney Pie", ItemIds.Manual_Recipe_KidneyPie_1),
        new ItemPickup(803, "Recipe: Kidney Stone 1", ItemIds.Manual_Recipe_KidneyStone_1),
        new ItemPickup(804, "Recipe: Kidney Stone 2", ItemIds.Manual_Recipe_KidneyStone_2),
        new ItemPickup(805, "Recipe: Leverpastej", ItemIds.Manual_Recipe_Leverpastej_1),
        new ItemPickup(806, "Recipe: Liver Patty Sandwich", ItemIds.Manual_Recipe_Leverpastejsmacka_1),
        new ItemPickup(807, "Recipe: Mac'n'Cheese", ItemIds.Manual_Recipe_MacNCheese_2),
        new ItemPickup(808, "Recipe: Maki", ItemIds.Manual_Recipe_Maki_1),
        new ItemPickup(809, "Recipe: Marshmallows", ItemIds.Manual_Recipe_Marshmellow_4),
        new ItemPickup(810, "Recipe: Mashed Potatoes", ItemIds.Manual_Recipe_MashedPotatoes_1),
        new ItemPickup(811, "Recipe: Mochi", ItemIds.Manual_Recipe_Mochi_1),
        new ItemPickup(812, "Recipe: Chocolate Mudcake", ItemIds.Manual_Recipe_Mudcake_1),
        new ItemPickup(813, "Recipe: Mushroom Omelette", ItemIds.Manual_Recipe_MushroomOmelette_2),
        new ItemPickup(814, "Recipe: Fried Mushroom 1", ItemIds.Manual_Recipe_MushroomsFried_1),
        new ItemPickup(815, "Recipe: Fried Mushroom 2", ItemIds.Manual_Recipe_MushroomsFriedSimple_1),
        new ItemPickup(816, "Recipe: Mushroom Soup 1", ItemIds.Manual_Recipe_MushroomSoup_1_1),
        new ItemPickup(817, "Recipe: Mushroom Soup 2", ItemIds.Manual_Recipe_MushroomSoup_4),
        new ItemPickup(818, "Recipe: Mushroom Soup 3", ItemIds.Manual_Recipe_MushroomSoupBroth_6),
        new ItemPickup(819, "Recipe: Mushroom Skewer", ItemIds.Manual_Recipe_MushroomsSkewer_2),
        new ItemPickup(820, "Recipe: Mystery Meat 1", ItemIds.Manual_Recipe_MysteryMeat_2_2),
        new ItemPickup(821, "Recipe: Mystery Meat 2", ItemIds.Manual_Recipe_MysteryMeat_2_3),
        new ItemPickup(822, "Recipe: Nashville Hot Chicken", ItemIds.Manual_Recipe_NashvilleHotChicken_3),
        new ItemPickup(823, "Recipe: Nigiri", ItemIds.Manual_Recipe_Nigiri_1),
        new ItemPickup(824, "Recipe: Omelette", ItemIds.Manual_Recipe_Omelette_1),
        new ItemPickup(825, "Recipe: Omelette fried in Butter", ItemIds.Manual_Recipe_OmeletteButter),
        new ItemPickup(826, "Recipe: Omelette with Cheese", ItemIds.Manual_Recipe_OmeletteCheese_1),
        new ItemPickup(827, "Recipe: Onigiri", ItemIds.Manual_Recipe_OnigiriFlesh_1),
        new ItemPickup(828, "Recipe: Peanut Butter", ItemIds.Manual_Recipe_PeanutButter_2_1),
        new ItemPickup(829, "Recipe: Pölsa 1", ItemIds.Manual_Recipe_Polsa_1),
        new ItemPickup(830, "Recipe: Pölsa 2", ItemIds.Manual_Recipe_Polsa_10),
        new ItemPickup(831, "Recipe: Porridge", ItemIds.Manual_Recipe_Porridge_1),
        new ItemPickup(832, "Recipe: Poutine", ItemIds.Manual_Recipe_Poutine),
        new ItemPickup(833, "Recipe: Ramen", ItemIds.Manual_Recipe_Ramen_2),
        new ItemPickup(834, "Recipe: Raclette", ItemIds.Manual_Recipe_Raqlette),
        new ItemPickup(835, "Recipe: Rhubarb Pie", ItemIds.Manual_Recipe_RhubarbPie_1),
        new ItemPickup(836, "Recipe: Rhubarb Porridge", ItemIds.Manual_Recipe_RhubarbPorridge_1),
        new ItemPickup(837, "Recipe: Puffed Rice Cakes", ItemIds.Manual_Recipe_RiceCakes_2),
        new ItemPickup(838, "Recipe: Butter Sandwich", ItemIds.Manual_Recipe_Sandwich_1),
        new ItemPickup(839, "Recipe: Sashimi 1", ItemIds.Manual_Recipe_Sashimi_1),
        new ItemPickup(840, "Recipe: Sashimi 2", ItemIds.Manual_Recipe_SashimiSandFish_1),
        new ItemPickup(841, "Recipe: Spicy Sausage 1", ItemIds.Manual_Recipe_Sausage_3),
        new ItemPickup(842, "Recipe: Spicy Sausage 2", ItemIds.Manual_Recipe_Sausage_4),
        new ItemPickup(843, "Recipe: Spicy Sausage 3", ItemIds.Manual_Recipe_Sausage_7),
        new ItemPickup(844, "Recipe: Sausage On Stick", ItemIds.Manual_Recipe_SausageOnStick_1),
        new ItemPickup(845, "Bites & bytes", ItemIds.Manual_RobotCooking),
        new ItemPickup(846, "Car Stereo", ItemIds.ValuableCarStereo),
        new ItemPickup(847, "Craw Guano", ItemIds.ValuableCrawGuano),
        new ItemPickup(848, "Diamond Ring", ItemIds.ValuableDiamondRing),
        new ItemPickup(849, "Drivers License", ItemIds.ValuableDriversLicense),
        new ItemPickup(850, "DVD Player", ItemIds.ValuableDVDPlayer),
        new ItemPickup(851, "Famous Painting", ItemIds.ValuableFamousPainting),
        new ItemPickup(852, "Fancy Watch", ItemIds.ValuableFancyWatch),
        new ItemPickup(853, "Fine China", ItemIds.ValuableFineChina),
        new ItemPickup(854, "Flatscreen TV", ItemIds.ValuableFlatscreenTV),
        new ItemPickup(855, "Gaming Laptop", ItemIds.ValuableGamingLaptop),
        new ItemPickup(856, "Gold Chain", ItemIds.ValuableGoldChain),
        new ItemPickup(857, "Golden Figurine", ItemIds.ValuableGoldenFigurine),
        new ItemPickup(858, "Golden Ticket", ItemIds.ValuableGoldenTicket),
        new ItemPickup(859, "MiniDisc Player", ItemIds.ValuableMinidisc),
        new ItemPickup(860, "MP3 Player", ItemIds.ValuableMP3Player),
        new ItemPickup(861, "Old Vintage", ItemIds.ValuableOldVintage),
        new ItemPickup(862, "Ornamental Vase", ItemIds.ValuableOrnamentalVase),
        new ItemPickup(863, "Poker Chips", ItemIds.ValuablePokerChips),
        new ItemPickup(864, "Silver Spoon", ItemIds.ValuableQuaintLittleSpoon),
        new ItemPickup(865, "Shav'Wa Soap", ItemIds.ValuableShavwaSoap),
        new ItemPickup(866, "Smartphone", ItemIds.ValuableSmartphone),
        new ItemPickup(867, "Soul Resin", ItemIds.ValuableSoulResin),
        new ItemPickup(868, "The Cost", ItemIds.ValuableTheCost),
        new ItemPrinter(869, "Arbiter 2", ItemIds.Weapon_Arbiter2),
        new ItemPrinter(871, "Augusta", ItemIds.Weapon_Augusta),
        new ItemPrinter(872, ".357 Balthazar", ItemIds.Weapon_Balthazar),
        new ItemPrinter(873, "Beck 8", ItemIds.Weapon_Beck),
        new ItemPickup(875, "Bo", ItemIds.Weapon_Bo),
        new ItemPrinter(876, "Breacher 8", ItemIds.Weapon_Breacher8),
        new ItemPrinter(877, "Bronco 89", ItemIds.Weapon_Bronco),
        new ItemPrinter(885, "Catacoil Rapid X", ItemIds.Weapon_Catacoil),
        new ItemPrinter(886, "Corpsemaker", ItemIds.Weapon_Corpsemaker),
        new ItemPickup(888, "Cryogenic Grenade", ItemIds.Weapon_CryoGrenade),
        new ItemPrinter(890, "D4RT", ItemIds.Weapon_D4RT),
        new ItemPrinter(891, "Deathstar PG", ItemIds.Weapon_DeathStar),
        new ItemPrinter(892, "P38 Dirk", ItemIds.Weapon_Dirk),
        new ItemPrinter(893, "Dolphin 99", ItemIds.Weapon_Dolphin99),
        new ItemPrinter(894, "Drifter 9", ItemIds.Weapon_Drifter9),
        new ItemPrinter(895, "Duhar", ItemIds.Weapon_Duhar),
        new ItemPickup(896, "Dynamite", ItemIds.Weapon_Dynamite),
        new ItemPrinter(898, "Farsight", ItemIds.Weapon_Farsight),
        new ItemPrinter(899, "Ferryman", ItemIds.Weapon_Ferryman),
        new ItemPrinter(900, "Flicker", ItemIds.Weapon_FlickerZip),
        new ItemPrinter(901, "Flock 76", ItemIds.Weapon_Flock),
        new ItemPrinter(909, "Gravekeeper", ItemIds.Weapon_Gravekeeper),
        new ItemPrinter(916, "Impala Gravita", ItemIds.Weapon_ImpalaGravita),
        new ItemPickup(917, "Jar of Love", ItemIds.Weapon_JarOfLove),
        new ItemPickup(918, "Katana", ItemIds.Weapon_Katana),
        new ItemPrinter(919, "Knop .22", ItemIds.Weapon_Knop),
        new ItemPrinter(920, "M11A2 Fisk", ItemIds.Weapon_M11Ramshack),
        new ItemPrinter(921, "Majordome", ItemIds.Weapon_Majordome),
        new ItemPrinter(922, "1889 Mario", ItemIds.Weapon_Mario),
        new ItemPickup(923, "Molotov Cocktail", ItemIds.Weapon_MolotovCocktail),
        new ItemPrinter(925, "Mossman", ItemIds.Weapon_Mossman),
        new ItemPrinter(926, "Neuraxis F22", ItemIds.Weapon_NeuraxisF22),
        new ItemPickup(928, "Nunchaku", ItemIds.Weapon_Nunchaku),
        new ItemPrinter(929, "Palehorse Topclipper", ItemIds.Weapon_PalehorseTopclipper),
        new ItemPrinter(930, "M182 Pierre-Fusil", ItemIds.Weapon_PierreFusil),
        new ItemPickup(931, "Pineapple Grenade", ItemIds.Weapon_PineappleGrenade),
        new ItemPrinter(932, "Ploika Compact", ItemIds.Weapon_PloikaC),
        new ItemPickup(933, "Jar of Poison", ItemIds.Weapon_PoisonGrenade),
        new ItemPickup(934, "Proximity Mine", ItemIds.Weapon_ProximityMine),
        new ItemPrinter(936, "Rektor 100rd", ItemIds.Weapon_Rektor),
        new ItemPrinter(938, "Rokua .308", ItemIds.Weapon_Rokua),
        new ItemPickup(939, "Sai", ItemIds.Weapon_Sai),
        new ItemPrinter(940, "Salamander", ItemIds.Weapon_Salamander),
        new ItemPrinter(943, "Snut .38", ItemIds.Weapon_Snut38),
        new ItemPrinter(944, "Socom 9", ItemIds.Weapon_Socom9),
        new ItemPrinter(945, "Star & Witness", ItemIds.Weapon_StarAndWitness),
        new ItemPickup(946, "Stick Grenade", ItemIds.Weapon_StickGrenade),
        new ItemPickup(947, "Sulfur Grenade", ItemIds.Weapon_SulfurGrenade),
        new ItemPrinter(948, "Tailor Marksman MKII", ItemIds.Weapon_TailorMarksman),
        new ItemPrinter(949, "M3 Termite", ItemIds.Weapon_Termite),
        new ItemPickup(950, "Throwing Knife", ItemIds.Weapon_ThrowingKnives),
        new ItemPrinter(952, "Type 80 Typhoon", ItemIds.Weapon_Typhoon),
        new ItemPrinter(953, "Unknown", ItemIds.Weapon_Unknown),
        new ItemPrinter(954, "Valet", ItemIds.Weapon_Valet),
        new ItemPrinter(955, "Vrede", ItemIds.Weapon_Vrede),
        new ItemPickup(956, "Wakizashi", ItemIds.Weapon_Wakizashi),
        new ItemPrinter(959, "Wyatt PULSAR", ItemIds.Weapon_WyattPulsar),
        new ItemPickup(961, "Stamp", ItemIds.Stamp),
        new ItemPickup(962, "Baptismal Font", ItemIds.Item_BaptismalFont),
        new ItemPickup(963, "Bulk Ammo Box", ItemIds.Item_BulkAmmoBox),
        new ItemPickup(964, "Chrismatory", ItemIds.Item_Chrismatory),
        new ItemPickup(965, "Gun Cabinet", ItemIds.Item_GunCabinet),
        new ItemPickup(966, "Snake Basket", ItemIds.Item_SnakeBasket),
        new ItemPrinter(967, "Longboy", ItemIds.Weapon_Longboy),
        new ItemPickup(968, "Toilet Paper", ItemIds.Item_Toiletpaper),
        new ItemPickup(969, "Toilet", ItemIds.Item_Toilet),
        new ItemPickup(970, "Small Golden Wall Frame", ItemIds.Item_Painting1),
        new ItemPickup(971, "Withered Wood Wall Frame", ItemIds.Item_Painting2),
        new ItemPickup(972, "Cherry Wood Wall Frame", ItemIds.Item_Painting3),
        new ItemPickup(973, "Luxurious Wall Frame", ItemIds.Item_Painting4),
        new ItemPickup(974, "Holoreality Projector", ItemIds.Item_HolorealityProjector),
        new ItemPickup(975, "Chrismatory Cost Reset", ItemIds.Item_ChristmatoryRefresh),
        new ItemPickup(976, "Delivery Demon Cost Reset", ItemIds.Item_DeliveryDemonRefresh),
        new ItemPickup(977, "Delivery Demon", ItemIds.Item_DeliveryDemon),
        new ItemPrinter(978, "Hell 'N' Back", ItemIds.Weapon_HellnBack),
        new ItemPrinter(979, "Wingman", ItemIds.Weapon_Wingman),
        new ItemPickup(980, "Additional Banish for Endless", ItemIds.Item_AddBanish),
        new ItemPickup(981, "Additional Choice Draw for Endless", ItemIds.Item_AddChoiceDraw),
        new ItemPickup(982, "Additional Re-roll for Endless", ItemIds.Item_AddReroll),
        new ItemPrinter(983, "Warpig", ItemIds.Weapon_Warpig),
        new ItemPrinter(984, "Cavalier", ItemIds.Weapon_Cavalier),
        new ItemSulf(985, "Cash Money Grand", 1000),
        new ItemPrinter(986, "Chat-Pardeur 98", ItemIds.Weapon_Chat_Pardeur98),
        new ItemPrinter(987, "Songbird", ItemIds.Weapon_Songbird),
        new ItemPrinter(988, "Socom ACR", ItemIds.Weapon_SocomACR),
        new ItemPickup(989, "SulfCola", ItemIds.Item_SulfCola),
        new ItemPickup(990, "Pilk", ItemIds.Item_Pilk),
        new ItemPickup(991, "Coffin", ItemIds.Item_Coffin),
        new ItemPickup(992, "Left Wall Mount", ItemIds.Item_WallMount0),
        new ItemPickup(993, "Center Wall Mount", ItemIds.Item_WallMount1),
        new ItemPickup(994, "Right Wall Mount", ItemIds.Item_WallMount2),
        new ItemPickup(995, "Laser Sight (Bone)", ItemIds.Attachment_LaserSightBone),
        new ItemPickup(996, "Laser Sight (Denim Blue)", ItemIds.Attachment_LaserSightDenimBlue),
        new ItemPickup(997, "Laser Sight (Light Blue)", ItemIds.Attachment_LaserSightLightBlue),
        new ItemPickup(998, "Laser Sight (Lime)", ItemIds.Attachment_LaserSightLime),
        new ItemPickup(999, "Laser Sight (Magenta)", ItemIds.Attachment_LaserSightMagenta),
        new ItemPickup(1000, "Laser Sight (Orange)", ItemIds.Attachment_LaserSightOrange),
        new ItemPickup(1001, "Laser Sight (Purple)", ItemIds.Attachment_LaserSightPurple),
        new ItemPickup(1002, "Laser Sight (Rose Pink)", ItemIds.Attachment_LaserSightRosePink),
        new ItemPickup(1003, "Laser Sight (Tangerine)", ItemIds.Attachment_LaserSightTangerine),
        new ItemPickup(1004, "Laser Sight (Teal)", ItemIds.Attachment_LaserSightTeal),
        new ItemPickup(1005, "Laser Sight (Poop)", ItemIds.Attachment_LaserSightPoop),
        new ItemPickup(1006, "Laser Sight (Gold)", ItemIds.Attachment_LaserSightGold),
        new ItemPrinter(1007, "Terrier URB.", ItemIds.Weapon_TerrierURB),
        new ItemPrinter(1008, "Blackwater", ItemIds.Weapon_Blackwater),
        new ItemPrinter(1009, "Chimera Rapid", ItemIds.Weapon_ChimeraRapid),
        new ItemPrinter(1010, "CYB47", ItemIds.Weapon_CYB47),
        new ItemPrinter(1011, "Death's Toll", ItemIds.Weapon_DeathsToll),
        new ItemCheckpoint(1013, "Unlock Church Grounds", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_01_Shanty),
        new ItemCheckpoint(1014, "Unlock Sewer shortcut", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_01_Sewers),
        new ItemCheckpoint(1015, "Unlock Hedge Maze shortcut", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_01_Hedgemaze),
        new ItemCheckpoint(1017, "Unlock Castle shortcut after Hedge Maze", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_01_Castle),
        new ItemCheckpoint(1018, "Unlock Forest shortcut", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_02_Forest),
        new ItemCheckpoint(1019, "Unlock Shav'Wani Fortress Bridge shortcut", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_02_Bridge),
        new ItemCheckpoint(1021, "Unlock Desert shortcut", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_03_Desert),
        new ItemCheckpoint(1022, "Unlock Beyond the Veil shortcut", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_03_EndChurch),
        new ItemCheckpoint(1023, "Unlock Town", "ReachedEnvironment_WorldEnvironment_Archipelago_ShantyUnlock"),
        new ItemCheckpoint(1024, "Unlock Dungeon entrance after Hedge Maze", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_01_Dungeon),
        new ItemCheckpoint(1025, "Unlock Sulfur Caves", "ReachedEnvironment_WorldEnvironment_" + WorldEnvironmentIds.Act_01_Caves),
    };

    private static readonly IDictionary<long, Item> ArchipelagoIdToItem =
        AllItems.ToDictionary(item => item.Id, item => item);
    private static readonly IDictionary<ItemId, Item> ItemIdToArchipelagoId =
        AllItems.Where(item => item is ItemPickup or ItemPrinter or ItemScroll)
            .ToDictionary(
                item => item.ItemId(),
                item => item
            );
    private static readonly IDictionary<string, Item> CheckpointToArchipelagoId =
        AllItems.Where(item => item is ItemCheckpoint)
            .ToDictionary(
                item => item.Checkpoint(),
                item => item
            );

    public static Item Get(long id)
    {
        return ArchipelagoIdToItem[id];
    }
    
    public static Item Get(ItemId itemId)
    {
        return ItemIdToArchipelagoId[itemId];
    }
    
    public static bool Has(ItemId itemId)
    {
        return ItemIdToArchipelagoId.ContainsKey(itemId);
    }

    public static Item Get(string checkpoint)
    {
        return CheckpointToArchipelagoId[checkpoint];
    }

    public abstract class AbstractItem
    {
        public abstract ItemId ItemId();
        public abstract string Checkpoint();
    }
    
    public abstract class Item : AbstractItem
    {
        public readonly long Id;
        public readonly string Name;
        public Action Action;

        public Item(long id, string name, Action<Item> action)
        {
            Id = id;
            Name = name;
            Action = () => action.Invoke(this);
        }

        public override ItemId ItemId() => throw new NotImplementedException();
        public override string Checkpoint() => throw new NotImplementedException();
    }

    private class ItemCheckpoint(long id, string name, string checkpoint)
        : Item(id, name, ItemHandler.UnlockCheckpoint)
    {
        public override string Checkpoint() => checkpoint;
    }

    private class ItemPickup(long id, string name, ItemId itemId)
        : Item(id, name, ItemHandler.HandleActualItem)
    {
        public override ItemId ItemId() => itemId;
    }

    private class ItemSulf(long id, string name, int amount)
        : Item(id, name, item => ItemHandler.HandleSulf(item, amount));

    private class ItemScroll(long id, string name, ItemId itemId)
        : Item(id, name, ItemHandler.HandleScholarUnlock)
    {
        public override ItemId ItemId() => itemId;
    }

    private class ItemPrinter(long id, string name, ItemId itemId)
        : Item(id, name, ItemHandler.HandleTeliaUnlock)
    {
        public override ItemId ItemId() => itemId;
    }
}